name: spacchiofy
description: "Music streaming application."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sutils:
    # git: https://github.com/StronzLabs/SUtils.git
    path: C:\Users\bonfr\Desktop\sutils
  package_info_plus: ^8.1.2
  background_downloader: ^8.6.0
  win32_registry: ^1.1.5
  url_launcher: ^6.3.1
  process_run: ^1.2.2+1
  connectivity_plus: ^6.1.1
  wakelock_plus: ^1.2.10
  flutter_svg: ^2.0.16
  html: ^0.15.5
  async: ^2.11.0
  just_audio: ^0.9.42
  just_audio_windows: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
